export const LOGIN = '[AUTH] LOGIN'
export const REGISTER = '[AUTH] REGISTER'
export const LOGOUT = '[AUTH] LOGOUT'
export const UPDATE_PROFILE = '[AUTH] UPDATE_PROFILE'
export const UPDATE_AVATAR = '[AUTH] UPDATE_AVATAR'
export const CHECK_AUTH = '[AUTH] CHECK_AUTH'

export const FETCH_POST = '[POST] FETCH_POST'
export const CREATE_POST = '[POST] CREATE_POST'
export const UPDATE_POST = '[POST] UPDATE_POST'
export const DELETE_POST = '[POST] DELETE_POST'
